# Generated by Django 5.0.4 on 2024-05-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_chefs_events_gallery_alter_dish_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishcategory',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
