# Generated by Django 5.0.4 on 2024-05-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_dishcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishcategory',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
