# Generated by Django 5.0.4 on 2024-05-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='time',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
